config/routes.rb
Bskb::Application.routes.draw do


  root :to => 'home#index'
  
  captcha_route

  get 'errors' => 'errors#index'

  resources :home, :only => :index  do 
    collection do
      get :form_test, :ajax_test, :test, :json_test
      post :form_test
    end
  end

  resources :json, :only => :index  do 
    collection do
      get :areas, :menus, :categories, :roles
    end
  end

  resources :uploads, :only => [:index, :create, :destroy]

  resources :users  do
    collection do
      get :sign_in, :sign_up, :sign_out, :forgot_password
      post :login, :create_user_dep, :valid_dep_name, :valid_user_login, :valid_captcha, :valid_user
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]

  namespace :kobe do
    resources :main, :only => :index do
      collection do
        get :to_do
      end
    end
    resources :orders
    resources :departments do 
      collection do
        get :ztree
        post :move, :valid_dep_name
      end
      member do 
        get :add_user, :freeze, :upload
        post :update_add_user, :update_freeze, :update_upload, :commit
      end
    end
    resources :articles do 
      collection do
        post :batch_task
      end
    end
    resources :menus do
      collection do
        get :ztree
        post :move
      end
    end
    resources :users, :except => :index do 
      member do
        get :reset_password, :show_logs, :freeze
        post :update_password, :save_freeze
      end
    end
    resources :categories do
      collection do
        get :ztree
        post :move, :valid_name
      end
    end
    resources :products
    resources :suggestions do
      post :mark_as_read, :mark_as_unread, on: :member
      collection do
        get :list
        post :batch_opt, :create_upload
        delete :destroy_upload
      end
    end
  end

  resources :shared do
    collection do
      delete :department, :area
      get :department, :area
    end
  end

  resources :kobe, :only => :index do
    collection do
      get :search, :obj_class_json
    end
  end






  

end

app/controllers/shared_controller.rb
# -*- encoding : utf-8 -*-
class SharedController < JamesController
	skip_before_action :verify_authenticity_token, :only => :get_ztree_title
	layout :false, :only => :get_ztree_title
	
  # 下拉框选择时查询行业分类
  def department
    ztree_json(Department)
  end

  # 下拉框选择时查询地区
  def area
    ztree_json(Area)
  end

  # ajax加载树形结构右侧展示页面的title 用于单位维护、品目参数维护
  def get_ztree_title
  	@obj = eval(params[:model_name]).find(params[:id])
  end

  private

end

app/helpers/my_form_helper.rb
# -*- encoding : utf-8 -*-
module MyFormHelper
  include BaseFunction

  def draw_myform(myform)
    set_top_part(myform) # 设置FORM头部
    set_input_part(myform) #设置主表input
    if myform.options.has_key?(:upload_files) && myform.options[:upload_files] == true
      set_upload_part(myform) # 设置上传附件
    else
      set_bottom_part(myform) # 设置底部按钮和JS校验
    end
    content_tag(:div, raw(myform.html_code).html_safe, :class=>'tag-box tag-box-v6')
  end

	def set_top_part(myform)
    myform.html_code << form_tag(myform.options[:action], method: myform.options[:method], class: 'sky-form no-border', id: myform.options[:form_id]).to_str
    unless myform.options[:title].blank?
      myform.html_code << "<div class='headline'><h2><strong>#{myform.options[:title]}</strong></h2></div>"
    end
	end

	def set_input_part(myform)
    myform.html_code << myform.get_input_part
	end

	def set_upload_part(myform)
		myform.html_code << %Q|
		<input id='#{myform.options[:form_id]}_uploaded_file_ids' name='uploaded_file_ids' type='hidden' />
		</form>|
		# 插入上传组件HTML
		myform.html_code << render(:partial => '/shared/myform/fileupload',:locals => {myform: myform})
	end

	def set_bottom_part(myform)
	  myform.html_code << myform.get_form_button
    myform.html_code << %Q|
    </form>
    <script type="text/javascript">
      jQuery(document).ready(function() {
        var #{myform.options[:form_id]}_rules = {#{myform.rules.join(",")}};
        var #{myform.options[:form_id]}_messages = {#{myform.messages.join(",")}};
        validate_form_rules('##{myform.options[:form_id]}', #{myform.options[:form_id]}_rules, #{myform.options[:form_id]}_messages);
      });
    </script>|
  end

  def get_button_part(myform,self_form=true)
    myform.get_form_button(self_form)
  end
	
end

app/views/shared/myform/_fileupload.html.erb
<%
form_id = myform.options[:form_id]
upload_model = myform.obj.class.upload_model
master_id = myform.obj.id
min_number_of_files = myform.options[:min_number_of_files]
rules = myform.rules
messages = myform.messages
%>
<div class="headline"><h2><strong><i class="fa fa-paperclip"></i> 上传附件</strong></h2></div>
<%= form_tag(uploads_path(master_id: master_id, upload_model: upload_model), multipart: true, id: "#{form_id}_fileupload", class: "sky-form fileupload_form no-border" ) %>
  <div class="fileupload-buttonbar">
    <div class="alert alert-warning  fade in">
      <%= raw upload_model.tips.html_safe %>
    </div>
    <div class="span7">
      <span class="pull-left btn btn-xs btn-success fileinput-button">
        <i class="fa fa-plus-circle"></i>
        <span>添加新文件</span>
        <input id="<%= "#{form_id}_upload_file_upload" %>" name="upload_file[upload]" type="file" />
      </span>
      <button type="submit" class="btn btn-xs btn-primary start">
        <i class="fa fa-upload"></i>
        <span>开始上传</span>
      </button>
      <button type="reset" class="btn btn-xs btn-warning cancel">
        <i class="fa fa-ban"></i>
        <span>取消上传</span>
      </button>
      <button type="button" class="btn btn-xs btn-danger delete">
        <i class="fa fa-trash-o"></i>
        <span>删除选中文件</span>
      </button>
      <label class="checkbox pull-right"><input type="checkbox" class="toggle"><i></i>选中全部文件</label>
    </div>
    <div class="span5">
      <div class="progress progress-striped active fade">
        <div class="bar progress-bar progress-bar-success" style="width:0%;"></div>
      </div>
    </div>
  </div>
  <div class="fileupload-loading"></div>
  <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
  </table>
  <%= raw get_button_part(myform,false).html_safe %>
</form>
<script type="text/javascript">
  jQuery(document).ready(function() {
    $("#<%= form_id %>_fileupload").fileupload(<%= upload_model.jquery_setting %>);
    $('#<%= form_id %>_submit').on('click',function(){
      var ids = $('form#<%= form_id %>_fileupload tr.template-download .preview[file_id]').map(function() {
        return $(this).attr('file_id');
      }).get().join(',');
      var minNumberOfFiles = <%= min_number_of_files.to_i %>;
      var alertContent = "<div class='alert alert-danger fade in'><button aria-hidden='true' data-dismiss='alert' class='close' type='button'>×</button><h4>出错了!</h4><p>上传附件没有达到数量要求（不少于"+ minNumberOfFiles +"个），请按要求上传附件。</p></div>";
      if (ids.split(",").length < minNumberOfFiles){
        if ($(this).prevAll("div.alert").length == 0){
          $(this).parent().prepend(alertContent);
        }
        return false;
      }else{
        $("#<%= form_id %>_uploaded_file_ids").val(ids);
        $('#<%= form_id %>').submit();
      }
    });
    $('#<%= form_id %>_reset').on("click",function(){$('#<%= form_id %>')[0].reset();});

    var <%= form_id %>_rules = {<%= raw rules.join(",").html_safe %>};
    var <%= form_id %>_messages = {<%= raw messages.join(",").html_safe %>};
    validate_form_rules('#<%= form_id %>', <%= form_id %>_rules, <%= form_id %>_messages);

  });
</script>

app/views/shared/myform/_fileupload_layout.html.erb
<!-- 显示准备上传的内容 -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="badge badge-red">{%=locale.fileupload.error%}！{%=locale.fileupload.errors[file.error] || file.error%}</span></td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar progress-bar progress-bar-success" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary btn-sm">
        <i class="fa fa-upload"></i>
        <span>上传</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning btn-sm">
        <i class="fa fa-ban"></i>
        <span>取消</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- 显示上传成功的内容 -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="badge badge-red">{%=locale.fileupload.error%}！{%=locale.fileupload.errors[file.error] || file.error%}</span></td>
        {% } else { %}
        <td class="preview" file_id="{%=file.id%}">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-xs btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="fa fa-trash-o"></i>
          <span>删除</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

app/views/shared/myform/_my_form.html.erb
<div class="tag-box tag-box-v6">
<%= form_tag(action, method: method, class: 'sky-form no-border', id: form_id) %>
<h2><strong><%= title %></strong></h2>
<hr />
<div class="row">
  <section class="col col-6"><label class="label">项目名称<span class="text-red">*</span></label>
    <label class="input">
      <i class="icon-append fa fa-info"></i>
      <input type="text" value="" name="orders[name]" id="orders_name">
      <b class="tooltip tooltip-bottom-right">项目名称应该包含主要产品信息，例如：XXX直属库输送机采购项目</b>
    </label>
  </section>
</div>
<input type="hidden" name="uploaded_file_ids" id="myform_uploaded_file_ids">
</form>
<hr />
</div>